rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/general_audio_documentation/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_linux/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_fucshia/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_macos/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_server/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_apis/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_android/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_ios/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_client/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_scheme/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_dart/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_assets_flutter/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_web/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_flutter/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_isar_scheme/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_cli/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_audio/package/general_audio_windows/LICENSE
