name: 'general_audio_flutter'
description: 'General Audio is library for recording, playing anything sound from any device and support backend without flutter ui because this library is bindings ffi miniaudio'
version: '0.0.2'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
homepage: 'https://github.com/{main_username_owner}/general_audio'
repository: 'https://github.com/{main_username_owner}/general_audio'
issue_tracker: 'https://github.com/{main_username_owner}/general_audio/issues'
documentation: 'https://github.com/{main_username_owner}/general_audio/tree/main/docs'
false_secrets:
  - 'android/jniLibs'
  - 'linux/'
  - 'windows/'
  - 'macos/'
  - 'ios/'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: 'flutter'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
project:
  type: ''
