name: 'general_audio_dart'
description: 'general_audio is program for help you, booster up your projects significants'
version: '0.0.2'
homepage: 'https://github.com/General-Developer/general_audio'
repository: 'https://github.com/General-Developer/general_audio'
issue_tracker: 'https://github.com/General-Developer/general_audio/issues'
documentation: 'https://github.com/General-Developer/general_audio/tree/main/docs'
funding:
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  path: '^1.9.0'
  general_audio: '^0.0.2'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
executables:
  general_audio: 'general_audio'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
