name: 'general_audio_dart'
description: 'General Audio is library for recording, playing anything sound from any device and support backend without flutter ui because this library is bindings ffi miniaudio'
version: '0.0.2'
homepage: 'https://github.com/{main_username_owner}/general_audio'
repository: 'https://github.com/{main_username_owner}/general_audio'
issue_tracker: 'https://github.com/{main_username_owner}/general_audio/issues'
documentation: 'https://github.com/{main_username_owner}/general_audio/tree/main/docs'
funding:
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  path: '^1.9.1'
  general_audio: '^0.0.2'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
project:
  type: ''
