include: package:lints/recommended.yaml
analyzer:
  exclude:
    - test
    - dev
    - templates
    - lib/core/core/interop/internal/generated/bindings.dart
linter:
  rules:
    - public_member_api_docs
