name: 'general_audio'
description: 'General Audio is library for recording, playing anything sound from any device and support backend without flutter ui because this library is bindings ffi miniaudio'
version: '0.0.2'
homepage: 'https://github.com/{main_username_owner}/general_audio'
repository: 'https://github.com/{main_username_owner}/general_audio'
issue_tracker: 'https://github.com/{main_username_owner}/general_audio/issues'
documentation: 'https://github.com/{main_username_owner}/general_audio/tree/main/docs'
funding:
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  ffi: '^2.1.4'
  build_runner: '^2.4.14'
  meta: '^1.16.0'
  io_universe: '^0.0.7'
  general_lib: '^0.0.67'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  mockito: '^5.4.5'
  coverage: '^1.11.1'
  ffigen: '^11.0.0'
  remove_from_coverage: '^2.0.0'
ffigen:
  name: 'NativeBindings'
  description: 'FFI bindings for native code'
  output: 'lib/core/core/interop/internal/generated/bindings.dart'
  preamble: |
    // coverage:ignore-file
  compiler-opts:
    - '-I../../native_lib/miniaudio/extras/miniaudio_split'
  headers:
    entry-points:
      - '../../native_lib/src/general_audio.h'
      - '../../native_lib/src/ca_dart.h'
      - '../../native_lib/src/ca_context.h'
      - '../../native_lib/src/ca_device.h'
      - '../../native_lib/src/ca_log.h'
      - '../../native_lib/miniaudio/extras/miniaudio_split/miniaudio.h'
  functions:
    include:
      - 'general_audio_.*'
      - 'ca_.*'
      - 'ma_.*'
      - 'Dart_InitializeApiDL'
    leaf:
      include:
        - 'ca_.*'
        - 'ma_.*'
        - 'Dart_InitializeApiDL'
      exclude:
        - 'ma_encoder_.*'
        - 'ma_decoder_.*'
  structs:
    include:
      - 'ca_.*'
      - 'ma_.*'
    member-rename:
      .*:
        _(.*): '$1'
  unions:
    include:
      - 'ca_.*'
      - 'ma_.*'
    member-rename:
      .*:
        _(.*): '$1'
  enums:
    include:
      - 'ca_.*'
      - 'ma_.*'
    member-rename:
      .*:
        _(.*): '$1'
  unnamed-enums:
    include:
      - 'ca_.*'
      - 'ma_.*'
  macros:
    include:
      - 'ca_.*'
      - 'ma_.*'
  globals:
    include:
      - 'ca_.*'
      - 'ma_.*'
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
  ffigen: '^11.0.0'
project:
  type: ''
